---
title: "**T**eam for **A**ssessing **I**mpacts to **L**iving resources from offshore **WIND** turbine**S**"
---

## Executive Summary
During the next 8 years, 2021 – 2029, US Wind, Inc. will undertake development of Lease area OCS-A 0490. In tandem with this development, UMCES will undertake a coordinated program of fishery resource and marine mammal monitoring. This plan was informed by extensive planning with US Wind administrators and advances state-of-the-science acoustic technologies and experimental design elements. The program includes monitoring of (1) commercial and recreational fishery resources, with a focus on black sea bass; (2) marine mammals (cetaceans: whales, dolphins and porpoises), using a passive acoustic monitoring array and emphasizing large whales, such as the endangered right whales, and dolphins; and (3) near real-time detections of baleen whales.

### Fishery Resource and Marine Mammal Monitoring 
The first two monitoring projects follow a BACI design, including (1) analysis of
US Wind’s metocean buoy sensor data for fish and marine mammal detections, and for the Fishery Resource Monitoring proposal a start-up period to test technologies and field deployments (2021- 2022), (2) before (2023-2024), during (2025-2026), and after periods (2027-2028); and (3) a data analysis and reporting wrap up phase (2029). The near real-time whale detection system will provide timely alerts on the presence of endangered whales for a 12-month sustained deployment (2022-2023) and continues monitoring with this buoy system that was initially constructed and deployed through Maryland state support. Field deployments for all monitoring projects utilize Ocean City commercial fishing and recreational charter vessels, as well as the UMCES R/V Rachel Carson. The Fishery Resource Monitoring project evaluates reef and spillover effects in a unique Before-After-Gradient design and for the first time tests ropeless gear in the black sea bass pot fishery. The Marine Mammal Monitoring project deploys two types of listening devices: Rockhopper recorders designed by Cornell University to determine the occurrence and position of large whales (including North Atlantic right whales) and dolphins, and F-POD devices to detect the tonal echolocation clicks of small cetaceans including porpoises. Additionally, this project will deploy biotelemetry receivers to listen for passing fishes, sharks, rays and turtles that have been implanted with transponders.

### Near Real-time Whale Monitoring
The Near Real-time Whale Monitoring project is a unique partnership between UMCES and Woods Hole Oceanographic Institution that utilizes specialized quiet mooring technology, whale vocalization detection algorithms, and telecommunications to transmit frequent alerts on the presence of baleen whales.

### Projected deliverables
Program deliveries include (1) database and analytical products related to project hypotheses and objectives; (2) extensive data sharing within the NOAA, BOEM, and offshore wind science community; (3) semi-annual progress and final reports for each project; and (4) professionally produced short videos of field deployments, diver footage, and stakeholder interviews related to black sea bass reef effects.
