---
title: "Marine Mammal Monitoring"
echo: false
warning: false
message: false

knitr:
  opts_knit:
    root.dir: "c:/users/darpa2/analysis/frm-survey"
execute: 
  freeze: auto
---



```{r}
library(sf)
library(geoarrow)
library(leaflet)
library(targets)
```
```{r}

towers <- st_read(tar_read(usw_locations),
                  layer = 'WTG_Layout_2022_0111',
                  quiet = T)
wms_enc <- 'https://gis.charttools.noaa.gov/arcgis/rest/services/MCS/ENCOnline/MapServer/exts/MaritimeChartService/WMSServer'
zones <- st_read(tar_read(usw_buildout),
                 quiet = T)

mmm <- read.csv('Data/GEO/mmm_sites.csv',
                na.strings = '') |> 
  st_as_sf(coords = c('longitude', 'latitude'), crs = 4326) |> 
  dplyr::mutate(type_name = as.factor(ifelse(is.na(type_name), 'MARU', type_name)))

leaflet() |> 
  setView(lng = -74.7, lat = 38.3, zoom = 10) |> 
  addWMSTiles(
    wms_enc,
    layers = c(0:3, 6),
    options = WMSTileOptions(format = "image/png", transparent = T)
  ) |>
  addPolygons(data = zones,
              group = 'Development Zone') |> 
  addCircleMarkers(data = towers, radius = 1, color = 'black') |>  
  addCircleMarkers(data = mmm, label = ~ site,
                   color = ~ colorFactor(c('red', 'orange', 'green'), mmm$type_name)(type_name),
                   group = 'type_name') |>
  # addLegend(data = mmm, pal = ~ colorFactor(c('red', 'orange', 'green'), mmm$type_name)) |> 
  addMeasure(primaryLengthUnit = 'meters', primaryAreaUnit = 'hectares') |>
  addMiniMap(zoomLevelFixed = 7)

```
