---
title: Meet the Fish (and friends)
---

Not just fish -- here are what you may find in our [commercial](../frm/#commercial) or [recreational](../frm/#recreational) fishery surveys:

## Fish

### Black sea bass {#bsb}

*Centropristis striata*

The focus of our survey, we're no stranger to this bass common to the Atlantic seaboard.

### Northern sea robin {#searobin}

*Prionotus carolinus*

### Cunner {#cunner}

*Tautogolabrus adspersus*

### Tautog {#tautog}

*Tautoga onitis*

### Scup {#scup}

*Stenotomus chrysops*

### Lined seahorse {#seahorse}

*Hippocampus erectus*

### Spotted hake {#hake}

*Urophycis regia*

## Crustaceans

### American lobster {#lobster}

*Homarus americanus*

### Jonah crab {#jonah}

*Cancer borealis*

### Mud crab {#mudcrab}

*Panopeidae* family

### Atlantic rock crab {#rockcrab}

*Cancer irroratus*

## Other

### Common sea star {#seastar}

*Asterias rubens*

### Common sand dollar {#sanddollar}

*Echinarachnius parma*

### Longfin squid {#squid}

*Doryteuthis pealeii*
