---
title: "Related publications and references"
---

## Baseline monitoring for migratory fishes

{{< ai open-access size=lg color=green >}} O’Brien, M.H.P., Secor, D.H., 2021. Influence of thermal stratification and storms on acoustic telemetry detection efficiency: a year-long test in the US Southern Mid-Atlantic Bight. Animal Biotelemetry 9, 8. [https://doi.org/10.1186/s40317-021-00233-3](https://doi.org/10.1186/s40317-021-00233-3)

{{< ai open-access size=lg color=green >}} Bangley, C.W., T.H. Curtis, D.H. Secor, M.B. Ogburn. 2020. Search for important habitat for juvenile dusky sharks (Carcharhinus obscurus) in the Northwest Atlantic Ocean using acoustic telemetry and spatial modeling. Marine and Coastal Fisheries 12:348-363. [https://doi.org/10.1002/mcf2.10120](https://doi.org/10.1002/mcf2.10120)

{{< ai open-access size=lg color=green >}} Fandel, A.D., A. Garrod, A.L. Hoover, J.E. Wingfield, V. Lyubchich, D.H. Secor, K.B. Hodge, A.N. Rice, And H. Bailey. 2020. Effects of intense storm events on dolphin occurrence and foraging behavior. Scientific Reports (2020) 10:19247 [https://doi.org/10.1038/s41598-020-76077-3](https://doi.org/10.1038/s41598-020-76077-3)

{{< ai open-access size=lg color=green >}} Rothermel, E.R., Balazik, M.T., Best, J.E., Fox, D.A., Gahagan, B.I., Haulsee, D.E., Higgs, A.L., O’Brien, M.H.P., Oliver, M.J., Park, I.A., and Secor, D.H. 2020. Comparative migration ecology of striped bass and Atlantic sturgeon in the US Southern Mid-Atlantic Bight flyway. PLOS ONE 15(6): e0234442. [https://doi.org/10.1371/journal.pone.0234442](https://doi.org/10.1371/journal.pone.0234442)

{{< ai open-access size=lg color=green >}} Secor, D, M O’Brien, E Rothermel, C Wiernicki, and H Bailey. “Movement and Habitat Selection by Migratory Fishes within the Maryland Wind Energy Area and Adjacent Reference Sites.” Sterling (VA): U.S. Department of the Interior, Bureau of Ocean Energy Management, Office of Renewable Energy Programs, 2020. URL: [https://espis.boem.gov/final%20reports/BOEM_2020-030.pdf](https://espis.boem.gov/final%20reports/BOEM_2020-030.pdf)

## Baseline monitoring for reef fishes

{{< ai open-access size=lg color=green >}} Secor, D.H., Bailey, H., Carroll, A., Lyubchich, V., O'Brien, M.H.P., Wiernicki, C.J., 2021. Diurnal vertical movements in black sea bass (Centropristis striata): Endogenous, facultative, or something else? Ecosphere 12, e03616. [https://doi.org/10.1002/ecs2.3616](https://doi.org/10.1002/ecs2.3616)


{{< ai open-access size=lg color=green >}} Wiernicki, C.J., O’Brien, M.H.P., Zhang F, Lyubchich V, Li M, Secor, D.H., 2020. The recurring impact of storm disturbance on black sea bass (Centropristis striata) movement behaviors in the Mid-Atlantic Bight. PLOS ONE 15(12): e0239919. [https://doi.org/10.1371/journal.pone.0239919](https://doi.org/10.1371/journal.pone.0239919)

{{< ai open-access size=lg color=green >}} Secor, D.H., Zhang, F., O’Brien, M.H.P. and Li, M. 2019. Ocean destratification and fish evacuation caused by a Mid-Atlantic tropical storm. ICES Journal of Marine Science, 76(2). [https://doi.org/10.1093/icesjms/fsx241](https://doi.org/10.1093/icesjms/fsx241)


## Guidance for offshore impacts on resource species

{{< ai open-access size=lg color=green >}} Responsible Offshore Science Alliance. 2021. Offshore Wind Project Monitoring Framework and Guidelines. URL: [https://www.rosascience.org/wp-content/uploads/2022/09/ROSA-Offshore-Wind-Project-Montioring-Framework-and-Guidelines.pdf](https://www.rosascience.org/wp-content/uploads/2022/09/ROSA-Offshore-Wind-Project-Montioring-Framework-and-Guidelines.pdf)

{{< ai open-access size=lg color=green >}} Hutchison, Z.L., D.H. Secor, and A.B Gill. 2020. The interaction between resource species and electromagnetic fields associated with electricity production by offshore wind farms. Oceanography 33(4):96-107. [https://doi.org/10.5670/oceanog.2020.409](https://doi.org/10.5670/oceanog.2020.409)

{{< ai closed-access size=lg color=pink >}} Wiernicki, CJ, D Liang, H Bailey, and DH Secor. 2020. The effect of swim bladder presence and morphology on sound frequency detection for fishes. Reviews in Fisheries Science and Aquaculture 28:459-477. [https://doi.org/10.1080/23308249.2020.1762536](https://www.tandfonline.com/doi/full/10.1080/23308249.2020.1762536)
